import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ city }) {
  return (
    <>
      <Head>
        <title>Online Cake Delivery in Mumbai, Pune and Mangalore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>{city}</main>
    </>
  );
}

export async function getServerSideProps(context) {
  try {
    const city = context.query.city;
    if (city) {
      return {
        redirect: {
          destination: `/${city}`,
          permanent: false,
        },
      };
    } else {
      return {
        redirect: {
          destination: "/mumbai",
          permanent: false,
        },
      };
    }
  } catch (error) {
    console.error("Error fetching category data:", error);
    return {
      props: {
        city: null,
      },
    };
  }
}
